name: 'Terraform Workflow'

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  terraform:
    name: 'Terraform Pipeline'
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v4

    # Step 2: Login to Azure
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Step 3: Setup Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    # Step 4: Terraform Init
    - name: Terraform Init
      run: terraform init

    # Step 5: Terraform Format Check
    - name: Check Terraform Format
      run: terraform fmt -check

    # Step 6: Terraform Validate
    - name: Validate Terraform Files
      run: terraform validate

    # Step 7: Generate Terraform Plan
    - name: Generate Terraform Plan
      run: terraform plan -out=terraform.plan

    # Step 8: Upload Terraform Plan (Optional for debugging in case of errors)
    - name: Upload Terraform Plan
      uses: actions/upload-artifact@v3
      with:
        name: terraform-plan
        path: terraform.plan

    # Step 9: Terraform Apply
    - name: Apply Terraform Plan
      if: github.event_name == 'push'
      run: terraform apply -auto-approve terraform.plan
